### ISSUE TITLE
Request Timeout on Webpack as a Service

### ISSUE THREAD

**Issue by tcaraccia** [moleculerjs/moleculer-web#72]
Hi,
Im trying to serve a vue app as a service following the conduit example.
I created a www.service.js inside services dir
**www.service.js**
```
"use strict";

let path = require("path");
const ApiGateway = require("moleculer-web");
const webpack = require("webpack");
const devMiddleware = require("webpack-dev-middleware");
const hotMiddleware = require("webpack-hot-middleware");
const serveStatic = require("serve-static");
const compression = require("compression");

const config = require("../webpack.config");
const compiler = webpack(config);

module.exports = {
	name: "www",
	middleware:false,
	mixins: [ApiGateway],
	settings: {
		port: 3000,
		routes: [
			{
				path: "/api",
				aliases: {
					"GET health": "$node.health",
				},
				bodyParsers: {
					json: true,
					urlencoded: { extended: true }
				}
			},
			{
				path: "/",
				use: [
					compression(),
					devMiddleware(compiler, {
						noInfo: true,
						publicPath: config.output.publicPath,
						headers: { "Access-Control-Allow-Origin": "*" }
					}),
					hotMiddleware(compiler),
					serveStatic(path.join(__dirname, "../public"))
				],
			},
		]
	}
};
```

App is being served correctly but I get response timeouts.
```
2018-08-16T13:25:30.190Z] INFO  desh-18794/WWW: => GET /app.js
[2018-08-16T13:25:30.326Z] INFO  desh-18794/WWW: => GET /__webpack_hmr
[2018-08-16T13:25:40.332Z] WARN  desh-18794/BROKER: Request 'www.rest' is timed out. { requestID: null, nodeID: 'desh-18794', timeout: 10000 }
[2018-08-16T13:25:40.334Z] ERROR desh-18794/WWW:    Request error! RequestTimeoutError : Request is timed out when call 'www.rest' action on 'desh-18794' node.
 RequestTimeoutError: Request is timed out when call 'www.rest' action on 'desh-18794' node.
    at p.timeout.catch.err (/home/sarodspirit/Development/mf-back/node_modules/moleculer/src/middlewares/timeout.js:33:13)
    at tryCatcher (/home/sarodspirit/Development/mf-back/node_modules/bluebird/js/release/util.js:16:23)
    at Promise._settlePromiseFromHandler (/home/sarodspirit/Development/mf-back/node_modules/bluebird/js/release/promise.js:512:31)
    at Promise._settlePromise (/home/sarodspirit/Development/mf-back/node_modules/bluebird/js/release/promise.js:569:18)
    at Promise._settlePromise0 (/home/sarodspirit/Development/mf-back/node_modules/bluebird/js/release/promise.js:614:10)
    at Promise._settlePromises (/home/sarodspirit/Development/mf-back/node_modules/bluebird/js/release/promise.js:689:18)
    at Async._drainQueue (/home/sarodspirit/Development/mf-back/node_modules/bluebird/js/release/async.js:133:16)
    at Async._drainQueues (/home/sarodspirit/Development/mf-back/node_modules/bluebird/js/release/async.js:143:10)
    at Immediate.Async.drainQueues (/home/sarodspirit/Development/mf-back/node_modules/bluebird/js/release/async.js:17:14)
    at runCallback (timers.js:781:20)
    at tryOnImmediate (timers.js:743:5)
    at processImmediate [as _immediateCallback] (timers.js:714:5)
Data: { action: 'www.rest', nodeID: 'desh-18794' }
[2018-08-16T13:25:40.334Z] WARN  desh-18794/WWW: Headers have already sent
```

Any clues about this ?

**Comment by molobala** [comment]
Which version of moleculer-web do you have?

**Comment by tcaraccia** [comment]
Sorry, I should have specified that before.
```
    "moleculer": "^0.13.1",
    "moleculer-db": "^0.7.5",
    "moleculer-db-adapter-mongoose": "^0.7.1",
    "moleculer-web": "^0.8.0"

```
Node  8.4.0

**Comment by molobala** [comment]
Try to uninstall and install moleculer-web to have the latest version 0.8.1

**Comment by tcaraccia** [comment]
Thanks!

**Comment by icebob** [comment]
It's weird because this problem was fixed in 0.8.1.
Could you try the vue example in this repo? Here: https://github.com/moleculerjs/moleculer-web/tree/master/examples/webpack-vue

If it's working and your's not and you don't find the problem, please make a reproduce repo and I will check it.

**Comment by tcaraccia** [comment]
I still can't find the issue.
Here is the  [reproduce repo](https://github.com/tcaraccia/moleculerweb-72)
Thanks very much!

**Comment by icebob** [comment]
Hmm, interesting. The problem is with `/__webpack_hmr` because webpack-hot-middleware doesn't close this response, it's a keep-alive request, so this request will be timed out. 
The same code "works" in moleculer-web examples because retry timeout is not configured.

**Comment by tcaraccia** [comment]
Ok, thanks for the follow up @icebob

**Comment by icebob** [comment]
Unfortunately I can't fix it.
